### PR TITLE
Attempt to get travis.ci to run

### PR DESCRIPTION
**Pull request by molecules**
This didn't install, so I was just trying to get travis.ci to run

### CODE REVIEW

**Comment by tony-o** [comment]
Were you using panda or zef?

**Comment by molecules** [comment]
panda

**Comment by molecules** [comment]
Here's an example of my installation attempt:

```
panda install Green
==> Fetching Green
==> Building Green
==> Testing Green
===SORRY!===
Cannot directly create a Supply. You might want:
 - To use a Supplier in order to get a live supply
 - To use Supply.on-demand to create an on-demand supply
 - To create a Supply using a supply block
t/00-use.t ...........
Dubious, test returned 1 (wstat 256, 0x100)
No subtests run
===SORRY!===
Cannot directly create a Supply. You might want:
 - To use a Supplier in order to get a live supply
 - To use Supply.on-demand to create an on-demand supply
 - To create a Supply using a supply block
t/01-time.t ..........
Dubious, test returned 1 (wstat 256, 0x100)
No subtests run
===SORRY!===
Cannot directly create a Supply. You might want:
 - To use a Supplier in order to get a live supply
 - To use Supply.on-demand to create an on-demand supply
 - To create a Supply using a supply block
t/02-concise.t .......
Dubious, test returned 1 (wstat 256, 0x100)
No subtests run
===SORRY!===
Cannot directly create a Supply. You might want:
 - To use a Supplier in order to get a live supply
 - To use Supply.on-demand to create an on-demand supply
 - To create a Supply using a supply block
t/03-more_concise.t ..
Dubious, test returned 1 (wstat 256, 0x100)
No subtests run

Test Summary Report
-------------------
t/00-use.t         (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
t/01-time.t        (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
t/02-concise.t     (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
t/03-more_concise.t (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
Files=4, Tests=0, 10 wallclock secs ( 0.05 usr  0.01 sys +  8.36 cusr  1.05 csys =  9.47 CPU)
Result: FAIL
The spawned process exited unsuccessfully (exit code: 1)
  in sub run-and-gather-output at /my/apps/perl6/rakudo-star-2016.07/install/share/perl6/site/sources/24811C576EF8F85E7672B26955C802BB2FC94675 (Panda::Common) line 85
  in block  at /my/apps/perl6/rakudo-star-2016.07/install/share/perl6/site/sources/48E2EB9144E069353B240AD2D147B48C65F70152 (Panda::Tester) line 22
  in sub indir at /my/apps/perl6/rakudo-star-2016.07/install/share/perl6/site/sources/24811C576EF8F85E7672B26955C802BB2FC94675 (Panda::Common) line 20
  in method test at /my/apps/perl6/rakudo-star-2016.07/install/share/perl6/site/sources/48E2EB9144E069353B240AD2D147B48C65F70152 (Panda::Tester) line 5
  in method install at /my/apps/perl6/rakudo-star-2016.07/install/share/perl6/site/sources/582CB7486602954A4601BDCE5A0EAC54B05DA58A (Panda) line 156
  in method resolve at /my/apps/perl6/rakudo-star-2016.07/install/share/perl6/site/sources/582CB7486602954A4601BDCE5A0EAC54B05DA58A (Panda) line 234
  in sub MAIN at /my/apps/perl6/rakudo-star-2016.07/install/share/perl6/site/resources/E0D978079BB5081DE986D058BB8AB08252F05CC8 line 18
  in block <unit> at /my/apps/perl6/rakudo-star-2016.07/install/share/perl6/site/resources/E0D978079BB5081DE986D058BB8AB08252F05CC8 line 151

```

**Comment by tony-o** [comment]
Hello - Please try installing again - I’ve just pushed the corrections for this to the git repo

Thank you,
Tony O’Dell | tony.odell@live.commailto:tony.odell@live.com

On Jul 26, 2016, at 1:42 PM, Christopher Bottoms <notifications@github.com<mailto:notifications@github.com>> wrote:

Here's an example of my installation attempt:

panda install Green
==> Fetching Green
==> Building Green
==> Testing Green
===SORRY!===
Cannot directly create a Supply. You might want:
- To use a Supplier in order to get a live supply
- To use Supply.on-demand to create an on-demand supply
- To create a Supply using a supply block
  t/00-use.t ...........
  Dubious, test returned 1 (wstat 256, 0x100)
  No subtests run
  ===SORRY!===
  Cannot directly create a Supply. You might want:
- To use a Supplier in order to get a live supply
- To use Supply.on-demand to create an on-demand supply
- To create a Supply using a supply block
  t/01-time.t ..........
  Dubious, test returned 1 (wstat 256, 0x100)
  No subtests run
  ===SORRY!===
  Cannot directly create a Supply. You might want:
- To use a Supplier in order to get a live supply
- To use Supply.on-demand to create an on-demand supply
- To create a Supply using a supply block
  t/02-concise.t .......
  Dubious, test returned 1 (wstat 256, 0x100)
  No subtests run
  ===SORRY!===
  Cannot directly create a Supply. You might want:
- To use a Supplier in order to get a live supply
- To use Supply.on-demand to create an on-demand supply
- To create a Supply using a supply block
  t/03-more_concise.t ..
  Dubious, test returned 1 (wstat 256, 0x100)
  No subtests run

## Test Summary Report

t/00-use.t         (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
t/01-time.t        (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
t/02-concise.t     (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
t/03-more_concise.t (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
Files=4, Tests=0, 10 wallclock secs ( 0.05 usr  0.01 sys +  8.36 cusr  1.05 csys =  9.47 CPU)
Result: FAIL
The spawned process exited unsuccessfully (exit code: 1)
  in sub run-and-gather-output at /my/apps/perl6/rakudo-star-2016.07/install/share/perl6/site/sources/24811C576EF8F85E7672B26955C802BB2FC94675 (Panda::Common) line 85
  in block  at /my/apps/perl6/rakudo-star-2016.07/install/share/perl6/site/sources/48E2EB9144E069353B240AD2D147B48C65F70152 (Panda::Tester) line 22
  in sub indir at /my/apps/perl6/rakudo-star-2016.07/install/share/perl6/site/sources/24811C576EF8F85E7672B26955C802BB2FC94675 (Panda::Common) line 20
  in method test at /my/apps/perl6/rakudo-star-2016.07/install/share/perl6/site/sources/48E2EB9144E069353B240AD2D147B48C65F70152 (Panda::Tester) line 5
  in method install at /my/apps/perl6/rakudo-star-2016.07/install/share/perl6/site/sources/582CB7486602954A4601BDCE5A0EAC54B05DA58A (Panda) line 156
  in method resolve at /my/apps/perl6/rakudo-star-2016.07/install/share/perl6/site/sources/582CB7486602954A4601BDCE5A0EAC54B05DA58A (Panda) line 234
  in sub MAIN at /my/apps/perl6/rakudo-star-2016.07/install/share/perl6/site/resources/E0D978079BB5081DE986D058BB8AB08252F05CC8 line 18
  in block <unit> at /my/apps/perl6/rakudo-star-2016.07/install/share/perl6/site/resources/E0D978079BB5081DE986D058BB8AB08252F05CC8 line 151

**Comment by molecules** [comment]
It now installs fine. Thanks!

**Pull request closed without merging**
